name: Testing

on:
  push:
    branches:
      - main  # Change to your branch if different
      - develop
      - feature

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Deploy Hook
        run: |
          curl -X POST https://api.render.com/deploy/srv-d113hjqli9vc738bsmf0?key=dTKMpUYYkPY

      - name: Move Jira task to "Done"
        run: |
          curl --request POST \
            --url https://parcial-2-ingycalidad.atlassian.net/rest/api/3/issue/SCRUM-4/transitions
            --user "${{ secrets.JIRA_EMAIL }}:${{ secrets.JIRA_API_TOKEN }}" \
            --header "Accept: application/json" \
            --header "Content-Type: application/json" \
            --data '{
              "transition": {
                "id": "31"
              }
            }'
